# Generated by Django 4.2.16 on 2024-10-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0003_remove_producto_nombre_proveedor_producto_proveedor'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('precio_unidad_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_tipo_docum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.tipodocumento')),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
