# Generated by Django 4.2.16 on 2024-10-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_nombre_proveedor_producto_proveedor'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='id_tipo_docum',
            new_name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='precio_total_venta',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='precio_unidad_venta',
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_documento',
            field=models.CharField(default='SIN DOCUMENTO', max_length=11),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unidad_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
