# Generated by Django 4.2.16 on 2024-10-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_rename_id_tipo_docum_factura_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='precio_total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_documento',
            field=models.CharField(default='', max_length=11),
        ),
    ]
