# Generated by Django 4.2.16 on 2024-10-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_factura_precio_total_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='actividad_comercial',
            field=models.CharField(default='Venta minorista de equipos de computación y telecomunicaciones.', max_length=255),
        ),
        migrations.AddField(
            model_name='factura',
            name='nit',
            field=models.CharField(default='700668550-5', max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_negocio',
            field=models.CharField(default='TEGNOFACIL', max_length=100),
        ),
    ]
