# Generated by Django 4.2.16 on 2024-10-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_factura_actividad_comercial_factura_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='actividad_comercial',
            field=models.CharField(default='Comercio al por menor de computadores, equipos periféricos y equipo de telecomunicaciones.', max_length=255),
        ),
    ]
