# Generated by Django 4.2.16 on 2024-09-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoservicio',
            name='proveedor',
        ),
    ]
