# Generated by Django 4.2.16 on 2024-09-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_remove_productoservicio_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='proveedores',
            field=models.ManyToManyField(related_name='productos', to='proveedor.proveedor'),
        ),
    ]
