# Generated by Django 4.2.16 on 2024-10-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0007_alter_factura_actividad_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNota',
            fields=[
                ('id_tipo_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nom_nota', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('tipo_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nota.tiponota')),
            ],
        ),
    ]
