# Generated by Django 4.2.16 on 2024-10-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_nombre_proveedor_producto_proveedor'),
        ('Nota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nota.nota')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
