# Generated by Django 4.2.16 on 2024-10-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_docum', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_doc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellidos_cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('documento_cli', models.CharField(max_length=11)),
                ('telefono', models.CharField(max_length=15)),
                ('id_tipo_docum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.tipodocumento')),
            ],
        ),
    ]
