# Generated by Django 4.2.16 on 2024-10-02 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_productoservicio_proveedores'),
        ('producto', '0002_rename_id_categoria_categoria_categoriaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
