# Generated by Django 4.2.16 on 2024-10-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_remove_pedido_precio_total_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Recibido', 'Recibido')], default='Pendiente', max_length=20),
        ),
    ]
